# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd4ba686641787a678a3f523407c6fe7a41612fceeb078a272e4ebab803c4aa9c1fb5871e9e85ed72c69951edf8d33b4e962e0dc6f11be50bedcd72a690bf590

test:
  secret_key_base: f3f5d69dcb4f3bdc8c677a2279c2cca3f49f1731d5686da863c3ef09a88fdb72c73f74381f830da8627df377ac8125d8e9a6ddc29767f5d5e2043c1ceec05666

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
